server:
  port: 8081

spring:
  application:
    name: pharmacy-service
  config:
    import: "optional:configserver:http://localhost:8888"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh
  endpoint:
    health:
      show-details: always

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [cid:%X{correlationId:-N/A}] %logger{36} - %msg%n"
  level:
    com.example.pharmacyservice: DEBUG
    io.github.resilience4j: DEBUG
